apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: exam
  labels:
    app: examapp

spec:
  clusterIP: None
  selector:
    app: examapp
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

