"""update

Revision ID: 3386f8edc410
Revises: 
Create Date: 2025-07-06 19:22:23.555998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3386f8edc410'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_exam_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_exam_status', schema=None) as batch_op:
        batch_op.drop_column('candidate_name')

    # ### end Alembic commands ###
