"""update

Revision ID: b41d51d3a1f0
Revises: 3386f8edc410
Create Date: 2025-07-06 19:33:35.359184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41d51d3a1f0'
down_revision = '3386f8edc410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_email', sa.String(length=100), nullable=True))

    with op.batch_alter_table('candidate_exam_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_exam_status', schema=None) as batch_op:
        batch_op.drop_column('candidate_email')

    with op.batch_alter_table('candidate_answers', schema=None) as batch_op:
        batch_op.drop_column('candidate_email')

    # ### end Alembic commands ###
