"""userid

Revision ID: c5562d9f9eb9
Revises: b41d51d3a1f0
Create Date: 2025-07-16 01:02:42.719174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5562d9f9eb9'
down_revision = 'b41d51d3a1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###
